# Generated by Django 2.0.2 on 2018-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(default='/static/beats/img/vinyl.png', upload_to='images/beats'),
        ),
    ]
