# Generated by Django 2.0.2 on 2018-08-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180807_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mcname',
            field=models.CharField(blank=True, max_length=50, verbose_name='MC name'),
        ),
    ]
