# Generated by Django 2.0.2 on 2018-08-08 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='likes',
        ),
        migrations.AddField(
            model_name='verse',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='verse_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
