# Generated by Django 2.0.2 on 2018-10-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0003_auto_20180921_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='image',
            field=models.ImageField(default='static/rhyme/img/rhymer_live.jpg', upload_to='images/verses'),
        ),
    ]
