# Generated by Django 2.0.2 on 2018-10-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_verse_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='image',
            field=models.ImageField(default='/rhyme/static/rhyme/img/rhymer_live.jpg', upload_to='images/verses'),
        ),
    ]
