# Generated by Django 2.0.2 on 2018-10-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
        ('verses', '0005_auto_20181010_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.Beat'),
        ),
    ]
