# Generated by Django 2.0.2 on 2018-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0006_verse_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='image',
            field=models.ImageField(default='/static/rhyme/img/rhymer_live.jpg', upload_to='images/verses'),
        ),
    ]
